export enum ServerResponseCode {
  INTERNAL_SERVER_ERROR_CODE = 'ER-1001',
  BAD_REQUEST_ERROR_CODE = 'ER-1002',
  VALIDATION_ERROR_CODE = 'ER-1003',
  FORBIDDENT_ERROR_CODE = 'ER-1004',
  COMMON_ERROR_CODE = 'ER-1005',
  TIME_OUT_ERROR_CODE = 'ER-1006',
  NOT_FOUND_ERROR_CODE = 'ER-1007',
}
